[package]
name = "powierza-distance"
authors = ["micouy <m.powierza@tutanota.com>"]
version = "0.1.0"
edition = "2018"


[[bench]]
name = "benches"
harness = false


[dependencies]


[dev-dependencies]
criterion = "0.3"
