[package]
name = "powierza-coefficient"
authors = ["micouy <m.powierza@tutanota.com>"]
version = "1.0.0"
edition = "2018"

[[bench]]
name = "benches"
harness = false

[dependencies]

[dev-dependencies]
criterion = "0.3"
strsim = "0.10"
